alphagov/govuk-jenkinslib

- README.md
- vars/govuk.groovy
I've been meaning to do this for a while but have never got round to it. Now I have about two weeks left, I intend to at least start the process.
Splitting this code out from the main govuk-puppet repository makes sense to me:
- Easier to understand the versioning and history away from the main Puppet repository
- Could potentially add some unit testing to the code itself
- The library could be loaded into a Jenkins instance without requiring all our Puppet code
- Makes it more visible! Maybe people are interested in how GOV.UK configure their applications for CI in Jenkins?
The process for pushing this change should hopefully be:
- Check how to load the library into Jenkins - load it in using a different name than the current
library
- Ensure that the library is automatically downloaded …
> Create dedicated repo for Jenkinslib

- vars/govuk.groovy
This was implemented by only used in two places:
* govuk_crawler_worker - this has now been revert to use standard release tags
* alphagov/release#Jenkinsfile - this flag will be removed in a future commit
This type of release naming caused problems during the deployment process, as
it was not fully rolled out we have instead decided to revert the changes.
Removing the implementation ensure we minimise the amount of tech debt.
> Remove all references to new style release tags

- vars/govuk.groovy
This uses the shellcheck tool to test shell scripts.
The method will default check *.sh files, but can be passed in specific paths to check. It can also be passed in with specific exclusions.
This kind of check should be specifically added for a repository.
> Add Shellcheck method

- vars/govuk.groovy
This PR makes the default `buildProject` run the [brakeman gem](https://brakemanscanner.org/) during all builds. 
Brakeman is a static analysis tool that will analyse the application and warn of any security issues. It detects things like possible SQL injections and other common attacks. It would have prevented https://github.com/alphagov/content-performance-manager/pull/526 from being introduced. Unfortunately, Brakeman sometimes surfaces false positives, so work may be required to rewrite code that brakeman thinks is fine.
To avoid instantly breaking the tests for all applications, the script currently reports the result of the security check separately to GitHub. This will allow us to fix any issues without disrupting the workflow. In a couple of weeks we should make a security check …
> Run security scan as part of the build process

- vars/govuk.groovy
If rubyLintDiff is false. For some reason, --cached becomes an invalid
option if --diff isn't used.
> Remove the --cached option along with the --diff option

- vars/govuk.groovy
To avoid breaking code which is calling this function directly.
> Specify the lintDiff default in rubyLinter as well

- vars/govuk.groovy
This should fix problems we're seeing with older base images which are causing builds to fail as we've set up the Dockerfile assuming a more recent build image.
> Always pull latest version when building a docker image

- README.md
- vars/govuk.groovy
This is a very simple check, but will hopefully suffice for the little time there is remaining before we move everything over to AWS (and so the same version of postgres).
This is just a simple text match, knowing nothing about the format of an ActiveRecord schema; so for instance a column called "brin" would be rejected.  But we only check the diff against master, which should help to reduce false positives; and it can always be disabled.
---
[Trello card](https://trello.com/c/sX8BEAR3/199-postgres-96-on-integration-follow-up)
> Add optional check for JSONB and BRIN in the database schema

- vars/govuk.groovy
This disables the `CheckRenderInline` brakeman check because it's giving out false positives.
CheckRenderInline is supposed to warn against controller code like this:
```rb
def show
render text: "You searched for #{params[:user_input]}"
end
```
In the context of controllers, `text` is a special option that will make Rails return a plain text response instead of HTML (like `render json: []` will render a JSON response). The method does not escape the user input, so is vulnerable to cross site scripting attacks.
However, in the GOV.UK components system, we use `text` as a local variable to be passed into a component. For example:
```ruby
<%= render "govuk_publishing_components/components/lead_paragraph", { text: @document.summary } %>
``` …
> Don't run the "render inline" check

- README.md
- vars/govuk.groovy
We've enabled Brakeman on all our apps individually now so we should start to run it automatically so that new apps will get the security checks.
[Trello Card](https://trello.com/c/JyrOAef3/363-fix-sql-injection-vulnerabilities-in-govuk-applications)
> Automatically run Brakeman for Rails apps

- vars/govuk.groovy
This results in quite a big speedup, on my system for example, for
Whitehall, it drops from ~40 seconds to ~8 seconds.
> Enable parallel linting for Ruby

- README.md
- vars/govuk.groovy
Rails apps have some specific linting checks in govuk-lint-ruby, which
new apps could benefit from - this shouldn't affect existing apps, as
we only lint the diff by default.
> Turn on rails-specific linting for ruby apps

- vars/govuk.groovy
These were removed in https://github.com/alphagov/govuk-jenkinslib/pull/21 and is causing jobs that use this method to fail e.g: https://github.com/alphagov/govuk-developer-docs/blob/master/Jenkinsfile#L39
> Set default args for rubyLinter

- vars/govuk.groovy
One specific directory that isn't normally linted is 'db', for which
we've seen some helpful checks fail in Content Publisher. This PR
enables us to extend the set of directories being linted by CI to better
match the local linting we do in development.
> Make dirs configurable for ruby linting

- vars/govuk.groovy
Currently these run by defualt if a Dockerfile exists, but this
results in doing unnecessary work for some repositories that contain a
Dockerfile, but one which isn't used (the seal is one example). This
should make it possible to disable the Docker related tasks, to avoid
the associated extra work and potential failures.
> Support disabling Docker related tasks

- vars/govuk.groovy
This should be specified in .rubocop.yml instead.
> Remove lintRails option for rubyLinter

- vars/govuk.groovy
The previous approach looks like this may have not detected when
bin/rails exists (for some unknown reason). The fileExists approach
seems to work though.
Also update the comment.
> Change Rails detection

- vars/govuk.groovy
Everything is on 2.5.1, so all we get by checking 2.3 is failed builds when things require a newer version of ruby, like the xray gem.
> Drop support for ruby-2.3

- vars/govuk.groovy
For an application that uses Mongoid, it can sometimes be necessary for the indexes to be there. Specifically, this is the case when using the geospatial modules https://docs.mongodb.com/manual/geospatial-queries/ where there has to be an index to perform these queries.
This is currently making the imminence tests flaky, as it depends on which `ci-agent` machine they run on, since only some of the databases have had those geospatial indexes built.
[Trello Card](https://trello.com/c/MdR10mng/424-fix-flakey-geo-indices-in-imminence-tests)
> Create Mongoid indexes when running tests

- vars/govuk.groovy
Rather than just checking what has changed. This works much better for
updates of the linting rules, as it means that Jenkins will check all
the code, ensuring that any issues are raised.
I've been going around and fixing linting issues in various
repositories, so I think as it's firebreak week, we can have a go at
changing the default (and fixing issues as and when they arise).
> Lint all the code by default

- vars/govuk.groovy
This takes up less space on the CI agents, and is faster, especially
for larger repositories.
> Shallow clone by default

- vars/govuk.groovy
The shallow clone means that Git thinks that the release branch
doesn't join up with the commit it's looking at locally. Therefore,
use --force-with-lease to make the git push work.
> Use --force-with-lease when updating the release branch

- vars/govuk.groovy
Sorry @cbaines! I just ran into a linting in the component gem. Do you mind if we make this default after all the repos have been fixed?
Reverts alphagov/govuk-jenkinslib#35
> Revert "Lint all the code by default"

- vars/govuk.groovy
This seems to cause issues when updating the release branch, and
possibly mirroring.
> Don't shallow clone when building master

- vars/govuk.groovy
This reverts https://github.com/alphagov/govuk-jenkinslib/pull/34 https://github.com/alphagov/govuk-jenkinslib/pull/37 and https://github.com/alphagov/govuk-jenkinslib/pull/39, because I think it's causing master to fail on Signon:
https://ci.integration.publishing.service.gov.uk/job/signon/job/master/1102/console
> Revert changes to clone / push

- vars/govuk.groovy
This takes up less space on the CI agents, and is faster, especially
for larger repositories. Shallow cloning for the master branch builds
causes issues with updating the release branch, so avoid this for
builds of the master branch.
This reverts commits 9b3a80287d2f48d600db3ea89d2a7a3c6da845ac,
7414b838e3393e373db70e6a2c230a74e66564db,
8a3cb08382524c660272e1ea04d62a00fb4cf087.
> Use shallow clones for building non-master branches

- vars/govuk.groovy
There's some value in merging the master branch, as this is a slightly
more rigorous test of the state that would result from merging the
branch. There's also value in only doing a shallow clone, as this
mitigates the space and time issues of constantly growing Git
repositories.
Currently, merging master is failing as Git doesn't have enough
information to perform the merge. I think if a newer version of Git
was in use, it would even refuse to attempt the merge.
Therefore, to try and get the best of both worlds, fetch more commits,
so that merging master works for most Pull Requests.
> Workaround merge issues with shallow clones

- vars/govuk.groovy
Since we now use Ruby 2.6 for GOV.UK apps we should test our gems against it
> Test gems against Ruby 2.6

- vars/govuk.groovy
I seem to find myself often in a situation where I open a PR without running the tests locally. Inevitably, my branch fails on CI because of a linting violation. I then go back to fix the linting issues and force-push. This time, the linter passes but a test fails, which requires me to do the same dance again.
This commit changes our build script to report the CSS and Ruby linter runs separately:
This means that 1) you can immediately see why your branch is failing, 2) you'll be able to see both linting and test runs at the same time, because the job doesn't stop after encountering a linter error. This should especially help with large test suites.
A downside is that _technically_ you could merge a PR with linter violations, because we haven't made the css-lint and ruby-lint checks …
> Report linting tasks separately

- vars/govuk.groovy
Reverts alphagov/govuk-jenkinslib#45. Turns out `govuk.pipelineTest` is actually used - by the tests for this repo.
> Revert "Remove unused code"

- vars/govuk.groovy
Move the precompile asset step before the testing step. Also set the
`RAILS_ENV=test` for asset precompilation.
In some of our applications such as government-frontend, we rely on
Capybara and Selenium to do some front end testing. When Capybara kicks
off, it tries to precompile assets if they aren't already precompiled.
This can take quite a while and sometimes causes `Net::ReadTimeout`
errors. If we instead precompile assets before Capybara runs, it will
use the precompiled assets and skip trying to precompile them. This
means we don't spend time during the first request waiting for
precompilation and we are less likely to hit the timeout.
Changing `RAILS_ENV` from `production` to `test` so that during testing
we use the precompiled assets. This shouldn't affect behaviour because
the …
> Precompile assets before testing

- vars/govuk.groovy
We're seeing the same timeout issues on schema tests as we did on standard branch tests.  Hopefully running precompile assets will fix this.
Example: https://ci.integration.publishing.service.gov.uk/job/government-frontend/job/deployed-to-production/124/console
> Net::ReadTimeout:         Net::ReadTimeout: Net::ReadTimeout with #<TCPSocket:(closed)>
test/test_helper.rb:197:in `visit_with_cachebust'
test/test_helper.rb:152:in `block in setup_and_visit_content_item'
test/test_helper.rb:150:in `tap'
test/test_helper.rb:150:in `setup_and_visit_content_item'
test/integration/document_collection_test.rb:5:in `block in <class:DocumentCollectionTest>'
> Precompile assets on schema tests too

- vars/govuk.groovy
The repo mirror has moved from Gitlab to AWS CodeCommit.  Code was still being pushed to Gitlab as part of the CI build.
> Remove push to Gitlab mirror

- vars/govuk.groovy
The build of `govuk-saas-config` is breaking.
I believe it's because we try to call the downstream job `integration-app-deploy` with the `application`argument being `govuk-saas-config`. 
However the downstream job expects the application name to be one defined in
https://github.com/alphagov/govuk-puppet/blob/a6ffb49be5895e1ef3f6c849384f09d1f7073e69/hieradata/common.yaml#L121 which does not include `govuk-saas-config`
We don't need this step for `govuk-saas-config` because it isn't a deployable application.
Add a condition around the "Deploy to integration" stage controlled by an option that we can pass in to `buildProject`. It should default to allow builds to continue as normal unless the option is set.
> Conditionally control deploying to integration

- README.md
Update the README with the new option skipDeployToIntegration that we
added in
https://github.com/alphagov/govuk-jenkinslib/commit/451d11b8c085b5d646d4ce788512b8977571c0af.
> Add skipDeployToIntegration param to README

- vars/govuk.groovy
We only have ruby 2.6.3 installed on our machines. I'm not aware of any external consumers of our gems
This should save about 3 minutes from a CI run of govuk_publishing_components
> Only test against used ruby versions

- README.md
- vars/govuk.groovy
This removes the option that only the diff of Ruby code can be linted.
We started the process to stop only linting diffs back in May 2018 with #9 when the option to turn off diffing was first created. An attempt was made to make this the default was done in #35 however this was reverted in #36 since it broke quite a few repos.
Nearly a year later we're more confident as the roll out of govuk-lint 4.0 alphagov/govuk-lint#126 has meant a significant amount of repos are now no longer diff linting and have meet current lint requirements.
There will no doubt still be a few things that fail due to this - I'm sorry - but this will help us move towards the world where we can consider adopting the outcome of https://github.com/alphagov/govuk-rfcs/blob/master/rfc-100-linting.md
I decided rather …
> Remove diff linting functionality

- vars/govuk.groovy
To speed up installing gems, pass the --jobs argument to bundle
install.
> Run bundle install in parallel

- README.md
- vars/govuk.groovy
This allows a custom Gam name to be specified, otherwise it defaults to the previous behaviour of using the repoName.
```groovy
node {
govuk.buildProject(
gemName: 'custom-gem-name'
)
}
```
> Add ability to specify custom Gem name

- vars/govuk.groovy
As `govuk-lint` will be deprecated, we need support RuboCop and sass-lint within our CI. This PR modifies the the linting stages to look for these tools and run them if appropriate. 
To support projects that haven't yet migrated away from `govuk-lint`, the linting stages will continue to use `govuk-lint`.
> Add support for RuboCop and scss-lint for linting

- vars/govuk.groovy
CI is failing because of a syntax error - a missing quote at the end of a string.
> Fix missing quotes on end of warning string

- vars/govuk.groovy
- The only usage of this was in govuk-aws before we [moved to
Concourse](https://github.com/alphagov/govuk-aws/pull/1233).
- Other places around GOV.UK use shellcheck, but via Rake tasks instead
of Jenkins config.
> Remove code to run shellcheck

- vars/govuk.groovy
- None of the apps we currently maintain on GOV.UK use `govuk-lint` to
lint their Ruby or SASS anymore.
- As a result, we can remove some complexity here! :tada:
> Remove govuk-lint commands and if statements

- vars/govuk.groovy
- This should be handled by the gem that sets the rest of the linter
config - `rubocop-govuk` - rather than the CI system.
- Leaving it to the CI system to decide which directories to lint is
confusing for developers - it's so far away from their day-to-day.
- Also, the setting was overrideable with an option specified in an
app's Jenkinsfile.
- The `rubocop-govuk` gem, as of v3.0.0, will set dirs to _not_ lint
specifically in .rubocop.yml which is clearer to people working on the
apps.
> lintRuby: Stop setting dirs to lint

- vars/govuk.groovy
Before:
```
/var/lib/jenkins/jobs/email-alert-monitoring/branches/remove-lin.emtbgpj0m4.-lint-call/builds/1/libs/govuk/vars/govuk.groovy: 567: unexpected token: lintRuby @ line 567, column 5.
def lintRuby {
^
```
> lintRuby: In Groovy, parentheses are significant

- vars/govuk.groovy
Before:
```
java.lang.NoSuchMethodError: No such DSL method 'lintRuby' found among steps [VersionNumber, ansiColor, archive, bat, build, catchError, ...........]
```
> lintRuby: Don't pass arguments when invoking the linter

- vars/govuk.groovy
- We've been collecting metrics via Statsd and pushing them into Graphite in the CI environment.
- A poll in Slack revealed that all respondents didn't realise we did this, and some didn't know where to look (https://ci-graphite.integration.publishing.service.gov.uk), so it's a fair assumption that no-one will miss them and we can remove some complexity from our Jenkins config.
It's useful to review this with `?w=1` as the query string when on the files tab, to discount all the whitespace changes.
> Don't collect metrics about runtimes for CI steps

- vars/govuk.groovy
Trello: https://trello.com/c/oNEtjIVp/99-serve-static-assets-from-www-hostname
This environment variable is no longer used in apps.
> Remove GOVUK_ASSET_HOST

- vars/govuk.groovy
This is now done as part of the default rake task for everything.
---
[Trello card](https://trello.com/c/5Gob6WUL/147-for-everyone-ensure-that-rubocop-runs-as-part-of-bundle-exec-rake-as-one-of-the-default-tasks)
> Remove lintRuby build step

- vars/govuk.groovy
We want to test the new AWS CI by running it in parallel with the current Carrenza CI. To avoid any confusion or blockage, we do not want AWS CI to report the status of the build to github as only the Carrenza CI build result is considered valid for now until we can ascertain that AWS CI is working properly.
> do not update github after jenkins tests in AWS CI

- vars/govuk.groovy
We're starting to run our apps with 2.7 so we should also start testing our Gems with that version too.
> Test Ruby gems with 2.7

- vars/govuk.groovy
`db:drop`:
- drops all the collections in the current env
https://github.com/mongodb/mongoid/blob/71abc955b20f05494947c38a11cc520ac712980f/lib/mongoid/railties/database.rake#L7-L10
`db:setup`:
- creates the database
- creates the indices
- seeds the db
https://github.com/mongodb/mongoid/blob/71abc955b20f05494947c38a11cc520ac712980f/lib/mongoid/railties/database.rake#L26-L29
At present, we rerun on an existing db with old state. This makes for confusing
errors.
> Run tests on a clean mongo database

- README.md
- vars/govuk.groovy
Trello: https://trello.com/c/MeG1zc2m/195-roll-out-stylelint-config-gds-across-govuk
It's common for GOV.UK Rails apps to have yarn dependencies, currently
many any apps have a hook of: `beforeTest: { sh("yarn install") },`. The
changes in this commit will mean this can be removed.
> Detect and install yarn dependencies automatically

- README.md
- vars/govuk.groovy
This check hasn't worked for a long time. For example:
```
[Pipeline] stage
[Pipeline] { (Check for Postgres 9.6 features)
[Pipeline] echo
Running Postgres 9.6 linter
[Pipeline] sh
+ git diff master master -- db/schema.rb
+ fatal: bad revision 'master'
grep -i brin
[Pipeline] sh
+ git diff master master -- db/schema.rb
+ grep -i jsonb
fatal: bad revision 'master'
[Pipeline] }
[Pipeline] // stage
```
There seems to be two problems: 1) Jenkins does a shallow checkout so
branches can't be found and 2) it seems to try compare master with
master so I'm not sure it could ever find a difference 🤷‍♂️.
Since I think it's exceedingly rare that GOV.UK apps are using Postgres
< 9.6 I don't think there is a need for this any longer.
> Remove non-functioning postgres96Lint

- vars/govuk.groovy
This is a branch that is being used to test out switching some GOV.UK projects from using a `master` branch to a `main` branch. To use it projects need to reference this branch when pulling in Jenkinslib and then specify in `buildProject` that the default branch is `main` - as per https://github.com/alphagov/maslow/pull/670/commits/6c900f74db2d5027bd4d88ea59edfbe23803b3fa
It did seem non-ideal to have to specify the default branch though I found it was a bit tricky to determine the default branch programatically. I found `git ls-remote --symref git@github.com:alphagov/stylelint-config-gds.git HEAD | grep 'ref:' | cut -d$'\t' -f1 | cut -d'/' -f3` (excuse my dubious bash) will do it without cloning the repo, but the git on our CI servers is too old to have `ls-remote`. Otherwise, once …
> Set-up for handling non-master default branches

- vars/govuk.groovy
The single quotes don't allow for interpolation which meant the $branch was
treated as undefined shell variable. Switching to double quotes fixes
this and resolves this error we were seeing:
```
+ git rev-list origin/
fatal: ambiguous argument 'origin/': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
+ git rev-parse HEAD
+ grep 7dd2357301eb757a2e4098295dfcfa528c360851
[Pipeline] echo
Current commit is not on main, so attempting merge of main branch before proceeding with build
```
> Fix broken interpolation

- vars/govuk.groovy
Currently we don't sufficiently unset RBENV_VERSION after setting
this environment variable.
This causes the pact tests for gds-api-adapters to fail.
The gds-api-adapters pact tests for Frontend raise the following
error when attempting to bundle install gems:
> Your Ruby version is 2.7.3, but your Gemfile specified 2.7.2
This happens because env.RBENV_VERSION is set to 2.7.3 by the
`testGemWithAllRubies` function in govuk groovy library:
https://github.com/alphagov/govuk-jenkinslib/blob/7d9befbef4b81e889fb7fb9f4562ec9afd730f30/vars/govuk.groovy#L674
All the apps that have pact tests use Ruby 2.7.2 but Frontend
includes the ruby version directive in its Gemfile, causing
bundler to raise an error:
https://github.com/alphagov/frontend/blob/9db830100d1c6712b87f1c7b3fbf646f174b1a66/Gemfile#L2 …
> Unset RBENV_VERSION after testing against a ruby version

- vars/govuk.groovy
testGemWithAllRubies leaves a Gemfile.lock file
generated by an incompatible version of bundler
raising the error:
Could not find 'bundler' (2.1.4) required by your
Gemfile.lock
The solution is to clean up the Gemfile.lock and
re-run bundle install before any afterTests
step if necessary.
> Bundle install before running after step for gems

- vars/govuk.groovy
Version v2.86 of the `workflow-cps` plugin extended the `UninstantiatedDescribable` class from
the `structs` plugin to store Groovy interpolated strings in an `UninstantiatedDescribableWithInterpolation` class. 
This was causing Jenkins to error immediately when building jobs as we have bespoke behaviour
for `UninstantiatedDescribables` which was not being applied.
This commit ensures we are able to handle both classes when building in Jenkins.
[PR introducing change to workflow-cps](https://github.com/jenkinsci/workflow-cps-plugin/pull/399)
[trello](https://trello.com/c/pCKvKF2J/2583-upgrade-jenkins-plugins-to-versions-without-security-vulnerabilities-5)
> Add UninstantiatedDescribableWithInterpolation to defaultParameterValuesMap

- vars/govuk.groovy
PR commit updates the Dockerfile Ruby version check to include `ARG base_image=ruby-X.Y.Z`, which we have recently added to allow the base image to use `govuk-ruby` in our `build-images` Concourse pipeline.
Trello: https://trello.com/c/dZQwFSKK
> Update Dockerfile Ruby version check

- vars/govuk.groovy
This PR replaces double quotes for single quotes to wrap the `s3cmd` which is passed to the `sh`ell step, as [recommended by the Jenkins docs](https://www.jenkins.io/doc/book/pipeline/jenkinsfile/#interpolation-of-sensitive-environment-variables) to avoid printing out sensitive data to logs. 
This manifests in our CI builds as a warning on the job status:
> Use single quotes to wrap s3cmd in shell step

- vars/govuk.groovy
This PR fixes the `sh` step so that the AWS secrets remain not outputted to logs, whilst allowing Groovy to interpolate `artefact_path` and `s3_path` normally.
> Fix quoting for local variables

- vars/govuk.groovy
We want to use a better base image than the community-supported Ruby ones, so that we can receive security updates promptly. This test was erronously asserting that we use the community-supported image.
Rollout: requires https://github.com/alphagov/govuk-puppet/pull/11678
Alternatives considered:
I started eliminating this nasty [change-detector] test by simply passing the Ruby version from `.ruby-version` to `docker build`, but then realised it'd be a lot of work to test given that we need to keep supporting the old Dockerfiles for the time being. The test will become obsolete anyway once we've given all the Dockerfiles the Replatforming treatment.
[change-detector]: https://testing.googleblog.com/2015/01/testing-on-toilet-change-detector-tests.html
> Accept `ARG ruby_version=` as an alternative to `FROM ruby:`.

- vars/govuk.groovy
Trello: https://trello.com/c/0FiI21om/2893-install-ruby-version-31-5
This change resolves two things:
1) It fixes a problem with newer versions of bundler that have a feature
of installing the requested version of bundler [1] and re-running
with that version (using the old command causes a write access issue:
Bundler::SudoNotPermittedError: Bundler requires sudo access to install at
the moment. Try installing again, granting Bundler sudo access when
prompted, or installing into a different path.)
2) It stops each build outputting deprecation warnings such as
`[DEPRECATED] The `--deployment` flag is deprecated because it relies
on being remembered across bundler invocations, which bundler will no
longer do in future versions. Instead please use `bundle config set
--local deployment …
> Replace deprecated commands with bundler suggestions

- vars/govuk.groovy
Reverts alphagov/govuk-jenkinslib#98
I'd forgotten we still support Ruby 1.9.3 (😱) for govuk-puppet. So this is going to need to be more complex in order to support both old and new rubies.
> Revert "Replace deprecated commands with bundler suggestions"

- vars/govuk.groovy
We have a new user `govukdockerci` which has been added to our
Enterprise hub and is an owner of the `govuk` organisation.
This should allow us to push without any limits. We will continue
to push to the existing govuk organisation that is owned by the
`govukci` user.
This avoids the disruption of having to recreate all the repos in
the governmentdigitalservice org which is shared across GDS.
The credentials have been added in [Jenkins CI](https://ci.integration.publishing.service.gov.uk/credentials/)
and has passed testing a [branch of government-frontend](https://github.com/alphagov/government-frontend/commit/4db1ceb9e47108eb5c9aca502f686d05a9c02b65),
see [console output](https://ci.integration.publishing.service.gov.uk/job/government-frontend/job/test-using-docker-enterprise-acc/6/conso …
> Use new Docker Enterprise user

- vars/govuk.groovy
This fixes the Docker ruby version check failing if the new GOV.UK Ruby base image is used.
https://trello.com/c/dwXqpVAi/968-base-and-builder-images
> Add support for GOV.UK Ruby base images in Docker ruby version check

- vars/govuk.groovy
We're consolidating all of GDS' Docker account usage so that it goes through governmentdigitalservice. This org has multiple owners and a process for requesting additional seats, etc, unlike the govuk org which has a 3 seat limit.
https://trello.com/c/6JRYK8hU/2982-push-to-pull-from-governmentdigitalservice-docker-org-3
> Push to & pull from governmentdigitalservice Docker org

- vars/govuk.groovy
This has been done to prevent the common headaches devs experience when they have a large PR, or collection of PRs that end up being more than 30 commits out of sync with the main branch.
In those cases developers are greeted with a rather unhelpful message of:
```
+ git merge --no-commit origin/main
fatal: refusing to merge unrelated histories
+ git merge --abort
fatal: There is no merge to abort (MERGE_HEAD missing).
```
As we don't have an agreement that there is a commit limit on PRs this arbitrary number is confusing and divisive (easily starts the debate on how big should a PR be).
This changes the approach to default to not having any limit at all and makes the limit an optimisation that repos can opt into. This means that repos calling `govuk.buildProject` will default to cloning …
> Make shallow clones a config option that defaults to false

- vars/govuk.groovy
This removes some quirky behaviour left for master branch handling, to reflect our switch to main as the default branch.
It removes a choice of shallow or not clone based on master branch and defaults to false, to continue the pattern that shallow clones are opted into. 
It defaults to shallow cloning a dependent branch since these are not going to need to be merged (at least in circumstances I can think of)
> Remove master branch quirks with shallow cloning

- vars/govuk.groovy
We're decommissioning the [Publishing E2E tests][] now that GOV.UK apps have transitioned to a model of continuous deployment with contract tests, as outlined in [RFC-128][]. The overall progress of this work is tracked in a [Trello card on the GOV.UK Tech Debt board][tech-debt-card].
This PR removes functionality from the `govuk.buildProject()` method that triggers the Publishing E2E tests to run against PRs in app repos. It stops the option `publishingE2ETests: true` from having any effect in the CI pipeline, as we no longer need them to run.
A [separate card exists][jenkinsfile-card] to tidy up the Jenkinsfile for each affected application.
[Publishing E2E tests]: https://github.com/alphagov/publishing-e2e-tests
[RFC-128]: https://github.com/alphagov/govuk-rfcs/blob/main/rfc-128-continu …
> Remove Publishing E2E tests from CI pipelines

- README.md
I forgot to update this in PR #120 / commit e99c76c19fb2c815bcb75e0ea55eac2933d62bc8 which actually removed the parameter from the code.
> Remove `publishingE2ETests` param from README

- vars/govuk.groovy
Trello: https://trello.com/c/amnaU0V9/853-decommission-the-publishing-end-to-end-tests
These functions are no longer used (confirmed by search on sourcegraph [1]) so can be removed from this repository.
There is one function that is deprecated that I left: deployIntegration as I found a number of references to that still [2].
[1]: https://sourcegraph.com/search?q=context:global+repo:alphagov&patternType=standard
[2]: https://sourcegraph.com/search?q=context:global+repo:alphagov+deployIntegration&patternType=standard
> Remove deprecated functions that are no longer used

- vars/govuk.groovy
This will ensure that newly triggered schema jobs are reported as pending rather than successes.
Also remove an unused bit of code.
> Fix status of pending job

- vars/govuk.groovy
This is no longer used, since
https://github.com/alphagov/govuk-puppet/pull/11954
> Remove Smokey Deploy logic
