vars/govuk.groovy

https://github.com/alphagov/govuk-puppet/pull/7288
Includes:
be5b6503c Parameter for selecting publishing-e2e-tests branch
a7ee7a962 Make the logRotator syntax more familiar
e20fe61e9 Change param definitions to use function calls

Pulling in changes from 7288

---

vars/govuk.groovy

Add method for testing this repository. I have to add it in two PRs because otherwise the tests will fail, so first we should add the method, and then have a separate PR to add the Jenkinsfile.

Add Jenkins test method

---

vars/govuk.groovy

Move the state to the inside of the conditional.

Only show the "Security analysis" phase if in use

---

vars/govuk.groovy

Remove unused code

---

vars/govuk.groovy

Reverts alphagov/govuk-jenkinslib#46, as it's causing some trouble on CI and I don't have time to fix it today.

Revert "Report linting tasks separately"

---

vars/govuk.groovy

This simplifies how we run Brakeman to use the version specified and installed by Bundler. Mostly this means builds are more reproducible as we always use the version specified in the `Gemfile.lock` rather than the version installed on CI.
I'm also hoping this will solve a problem we have with intermittent Brakeman runs where it doesn't seem to install properly.
[Trello Card](https://trello.com/c/qocdsaLD/1367-look-into-why-brakeman-occasionally-fails-on-test-runs)

Bundle exec brakeman if it's available

---

vars/govuk.groovy

https://trello.com/c/fq2LN9bl/153-rewrite-the-deploy-to-integration-job-so-it-can-be-used-for-cd
Reference: https://github.com/alphagov/govuk-puppet/pull/10361

Update integration deploy job to match Puppet

---

vars/govuk.groovy

Reverts alphagov/govuk-jenkinslib#75

Revert "do not update github after jenkins tests in AWS CI"

---

vars/govuk.groovy

Implement default branch detection

---

vars/govuk.groovy

Bundler has deprecated passing the without, path and deployment
arguments to bundle install. These will be removed in Bundler 3.
We also found that, when using a newer Bundler feature: auto install
[1], in our Ruby 3.1 builds that `bundle install` can fail with
permissions errors. I applied a change to fix this in adc5e6a.
However in that fix I overlooked that we actually use an extremely old
version of Ruby for govuk-puppet, 1.9.3 😭 - which is unlikely to change
soon.
So to resolve this I've gone for the rather complex change of adding a
conditional to check which version of Bundler is used. This meant the
dreaded process of doing a semvar comparison. I'm not knowledgable
enough to know if there is anything in Groovy's std library that could
make this easier, so I took a crude approach. …

Configure Bundler based on version used

---

vars/govuk.groovy

https://trello.com/c/JcY1L7so/2942-automatically-run-smokeydeploy-when-a-smokey-change-is-merged-3

Add step to deploy smokey to integration when changes are merged.

---

vars/govuk.groovy

Reverts alphagov/govuk-jenkinslib#102

Revert "Add step to deploy smokey to integration when changes are merged."

---

vars/govuk.groovy

Reverts alphagov/govuk-jenkinslib#103

Revert "Revert "Add step to deploy smokey to integration when changes are merged.""

---

vars/govuk.groovy

Reverts alphagov/govuk-jenkinslib#104

Revert "Revert "Revert "Add step to deploy smokey to integration when changes are merged."""

---

vars/govuk.groovy

Depends on https://github.com/alphagov/govuk-puppet/pull/11789
https://trello.com/c/JcY1L7so/2942-automatically-run-smokeydeploy-when-a-smokey-change-is-merged-3

Use Deploy_Smokey_Downstream job to deploy Smokey

---

vars/govuk.groovy

Reverts alphagov/govuk-jenkinslib#109

Revert "Push to & pull from governmentdigitalservice Docker org"

---

vars/govuk.groovy

We are moving to the governmentdigitalservice account but we want to make sure everything has been migrated before switching off the govuk account.
https://trello.com/c/6JRYK8hU/2982-push-to-pull-from-governmentdigitalservice-docker-org-3

Deploy to both docker accounts

---

vars/govuk.groovy

Trello: https://trello.com/c/amnaU0V9/853-decommission-the-publishing-end-to-end-tests
This change removes the building of a Dockerfile from the default
buildProject process. This has been done due to the retirement of the
publishing-e2e-tests which made use of these images [1].
There is a CI check that is lost due to this, the check that the Ruby
version in .ruby-version and the Dockerfile are the same version. I
talked to Chris Banks about this and the expectation is that the need
for this check will be removed by setting the ruby-version in the
Dockerfile with an argument. For example:
```
ARG ruby_version
ARG base_image=ghcr.io/alphagov/govuk-ruby-base:${ruby_version}
ARG builder_image=ghcr.io/alphagov/govuk-ruby-builder:${ruby_version}
FROM $builder_image AS builder
```
and built …

Remove building Dockerfile from the buildProject() process

---

vars/govuk.groovy

This is part of work to move content schemas into publishing api.
This PR introduces two bits of behaviour:
**The ability of apps to clone publishing api (or a specific branch of it) to run its schema validation tests against**
This will eventually replace the current behaviour which clones the govuk-content-schemas repo. For now, it should only happen when the USE_PUBLISHING_API_FOR_SCHEMAS env var is set to true.
The following two branches of travel-advice-publisher show this new behaviour in use and working:
* [Example of branch using govuk-content-schemas](https://github.com/alphagov/travel-advice-publisher/pull/1479)  as its source for schemas
* [Example of branch using publishing api ](https://github.com/alphagov/travel-advice-publisher/pull/1480) as its source of schemas, using the …

Add support for publishing api content schemas

---

vars/govuk.groovy

Content schemas have now been moved into publishing api, so we can remove the code for cloning govuk-content-schemas, as well as removing the temporary flag that was used to test switching to publishing api.
This change will switch all apps' CIs to using publishing api for schemas.
Blocked until [publishing api PR](https://github.com/alphagov/publishing-api/pull/2184) is merged ✅ 
[Trello](https://trello.com/c/ZUK2duYI/361-add-govuk-content-schemas-to-publishing-api-repo)

remove code for cloning govuk-content-schemas

---

vars/govuk.groovy

Trello: https://trello.com/c/QrxjshEm/270-move-ruby-gems-from-jenkins-to-github-actions
All of GOV.UK's gems are now built by GitHub Actions so we don't need this anymore. We're removing it so that new things can't creep back into Jenkins. Hopefully no-one ever sees this error.

Remove ability to build and deploy gems
